export const dummyDataOfBestProgects = [
  {
    id: 1,
    projectPagePath: '/#',
    projectImagePath: '/',
    userImagePath: '/',
    title: '독거노인을 위한 뭐시기 프로젝트',
    userName: '제갈두어',
  },
  {
    id: 2,
    projectPagePath: '/#',
    projectImagePath: '/',
    userImagePath: '/',
    title: '두어 프로젝트 ㅋ.ㅋ',
    userName: '이지원',
  },
  {
    id: 3,
    projectPagePath: '/#',
    projectImagePath: '/',
    userImagePath: '/',
    title: 'ㅇㄴ미ㅏ;ㅇㄴ마ㅣ;ㅇㄴ마ㅣ;',
    userName: '마이네임 이즈 민호',
  },
  {
    id: 4,
    projectPagePath: '/#',
    projectImagePath: '/',
    userImagePath: '/',
    title: 'ㅇㄴㅁㄴㅁ,ㅡㅜㄴ미ㅜ아ㅣㅇ넘어니머ㅏㅣㅇㄴ머ㅏㅣㄴㅇㅁ',
    userName: 'ㄴㅇㅁㅇㄴㅁㄴㅇㅁㄴㅇㅁㄴㅇㅁㅇㄴㅁ',
  },
];

export const dummyDataOfRecruitTeam = [
  {
    id: 1,
    recruitPagePath: '/#',
    projectImagePath: '/',
    teamImagePath: '/',
    keyword: '서비스종류 앱인지웹인지 키워드',
    teamName: '팀 제갈두어아으아아아',
    title: '가치관 기반 매칭 서비스 앱 파인드',
    job: '디자이너',
    duty: 'UI 디자이너',
    location: '서울특별시 강남구',
    date: '2021-08-10 00:00:00',
    like: true,
  },
  {
    id: 2,
    recruitPagePath: '/#',
    projectImagePath: '/',
    teamImagePath: '/',
    keyword: '서비스종류 앱인지웹인지 키워드',
    teamName: '팀 제갈두어아으아아아',
    title: '가치관 기반 매칭 서비스 앱 파인드ㄴㅁㅇㅇㄴㅁㄴㅁㅇㄴㅇㅁ ㄴㅁㅇ',
    job: '디자이너',
    duty: 'UI디자이너 UX디자이너 영상디자이너',
    location: '서울특별시 강남구',
    date: '2021-08-10 00:00:00',
    like: false,
  },
  {
    id: 3,
    recruitPagePath: '/#',
    projectImagePath: '/',
    teamImagePath: '/',
    keyword: '서비스종류 앱인지웹인지 키워드',
    teamName: '팀 제갈두어아으아아아',
    title: '가치관 기반 매칭 서비스 앱 파인드',
    job: '디자이너',
    duty: 'UI 디자이너',
    location: '서울특별시 강남구',
    date: '2021-08-10 00:00:00',
    like: true,
  },
];
